### ISSUE TITLE
Prepare a meaningful documentation for customization endpoints

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow-customization#2]
We need to prepare a reasonable intro into how to customize Web Flow, with following topics covered:

- How do I change appearance of my website?
   - Colors => "Edit main.css"
   - Images => "Create images and put them in images"
   - Fonts => "Create fonts folder and use fonts in main.css"
- How do I connect data adapter to my service?
    1. Asses your technology
    1. Checkout your project
    1. Modify pom.xml to have everything needed
    1. Create proprietary client (+ client config) for your service
    1. Implement "DataAdapter" interface

Do we need anything else?

**Comment by romanstrobl** [comment]
I wrote documentation for changing appearance of Web Flow:

https://github.com/lime-company/powerauth-webflow-customization/wiki/Customizing-Web-Flow-Appearance

Please check that the Spring boot + Tomcat configuration reflects current deployment by the client.

**Comment by romanstrobl** [comment]
And here is documentation for implementing Data Adapter interface:

https://github.com/lime-company/powerauth-webflow-customization/wiki/Implementing-the-Data-Adapter-Interface
