### ISSUE TITLE
Remove fetchBankAccounts method

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-webflow-customization#8]
Data adapter in it's base for should be domain agnostic. The method `fetchBankAccounts` is too tightly coupled with banking domain.

We should replace it by method such as:

```java
public OperationFormData decorateFormData(String userId, String operationName, String operationId, OperationFormData formData) throws UserNotFoundException, DataAdapterRemoteException;
```

It would process form data and return "decorated" form data with any additional attributes it requires.

**Comment by romanstrobl** [comment]
Issue is related to: https://github.com/lime-company/powerauth-webflow/issues/106

**Comment by romanstrobl** [comment]
Issues is fixed in https://github.com/lime-company/powerauth-webflow/pull/332
